version: '3.9'
services:  
  flask_web:
    container_name: flask_web_container
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/home/app/
    restart: unless-stopped
    depends_on: 
      - postgres

  postgres:
    env_file: ./docker/.env-postgresql
    container_name: postgres_flask_container
    image: postgres:14
    volumes:
       - flaskdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    restart: unless-stopped
    networks:
      - backend
  
volumes:
    flaskdb:
      driver: local

networks:
  backend:
    driver: bridge