"""empty message

Revision ID: e29333ae0034
Revises: b6b9426b28c3
Create Date: 2025-02-25 19:49:03.904190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision = 'e29333ae0034'
down_revision = 'b6b9426b28c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    classes = table('classes',
                    column("class_name", String),
                    column("class_parral", Integer))
    classes_list = [{"class_name": str(num) + let, "class_parral": num} for num in range(5,12) for let in 'АБВГ']
    classes_list.insert(9, {"class_name": '6Д', "class_parral": 6})
    op.bulk_insert(classes,
       classes_list
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM classes")

    # ### end Alembic commands ###
